### ISSUE TITLE
Linux audio set-up instructions

### ISSUE THREAD

**Issue by dkobozev** [wyager/LEDStrip#1]
Could you please add some information about setting up the audio for this project on Linux? You mentioned snd-aloop and JACK's monitor interfaces in your blog post, but my knowledge of Linux audio isn't sufficient to make that work.

**Comment by wyager** [comment]
Sure. I set this up a while ago, but I'll add a blurb in the README.

**Comment by dkobozev** [comment]
Thanks for updating the info. After I spent a bit of time trying to wrap my head around all the components of the Linux sound system, I realized that I don't need to deal with `snd-aloop` or JACK because I have PulseAudio installed on my system. Getting `led_driver.py` to capture audio was a simple matter of launching `pavucontrol`, selecting the Recording tab and choosing Monitor of Built-In Audio Analog Stereo while `led_driver.py` was running. [Audacity's wiki](http://manual.audacityteam.org/o/man/tutorial_recording_computer_playback_on_linux.html) was helpful.

**Comment by wyager** [comment]
Awesome! I'll add a note to the readme.

**Comment by lakeflower** [comment]
Hi, I have PulseAudio and did the same as @dkobozev with launching `pavucontrol` and select Monitor of Built-In Audio Analog Stere while `led_driver.py` was running. The LED:s are flashing a little bit, but not in time with the music and I still get the error "jack server is not running and cannot be started".
Any suggestions? Do I need to manipulate the `led_driver.py` file?

**Comment by wyager** [comment]
It's unlikely that `led_driver.py` is related to the error you're getting. If you google `jack server is not running and cannot be started`, there are a ton of SO threads. Perhaps try some of those?

**Comment by lakeflower** [comment]
Hi, yeah I tested that and found this [stackoverflow.com/.../pyaudio-working-but-spits-out-error-messages-each-time](http://stackoverflow.com/questions/7088672/pyaudio-working-but-spits-out-error-messages-each-time) that was exactly the problem. Perhaps you could consider do something similar to get rid of the errors.
However, the errors didn't affect the result, it actually works for me some times ( :D yay). The problem was that there seems to be an enormous delay time from playing the audio to the LED:s to react. About 30 sec. The first time I started the script it worked great, but pretty soon it added up with a lot of latency. It still does some weird random flashing though and sometimes it just blacks out for a while.

One problem could be that I'm just using three LED:s right now, while the script was designed for a lot more. That could explain why they black out sometime, but it doesn't explain the randomness...

I guess another problem could be that I'm on an old EeePc running Lubuntu. Maybe it's too heavy calculations? The LED:s are smart pixels and blinkstick pro [www.blinkstick.com](www.blinkstick.com).

Just want to thank you for the support, I'm not that experienced with Python and this means a lot to get me in the right direction! cheers

**Comment by wyager** [comment]
Does the delay increase the longer you run the program?

**Comment by lakeflower** [comment]
It's hard to say, it seems relatively random. It's blacking out for a while and then suddenly it flashes a lot and then it fades out again. Sometimes it starts to flash about 30 sec after I started the music.

That's why I thought that the "non existing" LED:s where flashing on other visualizer frequencies, but while it's so inconsequent I start to wonder.

Is there a way to optimize for fewer LED:s? I plan to use about 5-10 :)

**Comment by wyager** [comment]
Unfortunately I can't really help much without knowing how you've modified the software to support the different LED configuration.
